version: '3.7'

services:
  db:
    container_name: SocialMediaDB
    image: postgres:latest
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_TEST}

volumes:
  db:
