version: '3.7'

services:
  db:
    container_name: SocialAuthDB
    image: postgres:12.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_TEST}

volumes:
  db:
