version: '3.8'

services:
  db:
    container_name: SocialAuthDb
    image: postgres:15.2
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES="${DB_DEV}","${DB_TEST}"

volumes:
  db:
