name: Test

on: [push]

jobs:

  backend-lint:
    name: Backend lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Run lint
        run: npm run lint
        working-directory: ./backend
        env:
          CI: true

  backend-tests:
    name: Backend unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Run tests
        run: npm run test:cov
        working-directory: ./backend
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true

  backend-e2e-tests:
    name: Backend E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup docker
        run: docker-compose --f docker-compose.ci.yml up
        working-directory: ./docker
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Run tests
        run: npm run test:e2e:cov
        working-directory: ./backend
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        env:
          CI: true
